In [5]:
import pandas as pd

In [6]:
df_gp = pd.read_csv("global_power_plant_database.csv")

df_gp = df_gp.dropna(axis='columns', how='all')

print(df_gp.head())

print("Column names:\n", df_gp.columns)

  country country_long                                              name  \
0     AFG  Afghanistan      Kajaki Hydroelectric Power Plant Afghanistan
1     AFG  Afghanistan                                      Kandahar DOG
2     AFG  Afghanistan                                      Kandahar JOL
3     AFG  Afghanistan     Mahipar Hydroelectric Power Plant Afghanistan
4     AFG  Afghanistan  Naghlu Dam Hydroelectric Power Plant Afghanistan

      gppd_idnr  capacity_mw  latitude  longitude primary_fuel other_fuel1  \
0  GEODB0040538         33.0    32.322    65.1190        Hydro         NaN
1    WKS0070144         10.0    31.670    65.7950        Solar         NaN
2    WKS0071196         10.0    31.623    65.7920        Solar         NaN
3  GEODB0040541         66.0    34.556    69.4787        Hydro         NaN
4  GEODB0040534        100.0    34.641    69.7170        Hydro         NaN

  other_fuel2  ... estimated_generation_gwh_2013  \
0         NaN  ...                        123.77
1         NaN  ...                         18.43
2         NaN  ...                         18.64
3         NaN  ...                        225.06
4         NaN  ...                        406.16

   estimated_generation_gwh_2014 estimated_generation_gwh_2015  \
0                         162.90                         97.39
1                          17.48                         18.25
2                          17.58                         19.10
3                         203.55                        146.90
4                         357.22                        270.99

  estimated_generation_gwh_2016 estimated_generation_gwh_2017  \
0                        137.76                        119.50
1                         17.70                         18.29
2                         17.62                         18.72
3                        230.18                        174.91
4                        395.38                        350.80

  estimated_generation_note_2013 estimated_generation_note_2014  \
0                       HYDRO-V1                       HYDRO-V1
1                SOLAR-V1-NO-AGE                SOLAR-V1-NO-AGE
2                SOLAR-V1-NO-AGE                SOLAR-V1-NO-AGE
3                       HYDRO-V1                       HYDRO-V1
4                       HYDRO-V1                       HYDRO-V1

   estimated_generation_note_2015  estimated_generation_note_2016  \
0                        HYDRO-V1                        HYDRO-V1
1                 SOLAR-V1-NO-AGE                 SOLAR-V1-NO-AGE
2                 SOLAR-V1-NO-AGE                 SOLAR-V1-NO-AGE
3                        HYDRO-V1                        HYDRO-V1
4                        HYDRO-V1                        HYDRO-V1

   estimated_generation_note_2017
0                        HYDRO-V1
1                 SOLAR-V1-NO-AGE
2                 SOLAR-V1-NO-AGE
3                        HYDRO-V1
4                        HYDRO-V1

[5 rows x 36 columns]
Column names:
 Index(['country', 'country_long', 'name', 'gppd_idnr', 'capacity_mw',
       'latitude', 'longitude', 'primary_fuel', 'other_fuel1', 'other_fuel2',
       'other_fuel3', 'commissioning_year', 'owner', 'source', 'url',
       'geolocation_source', 'wepp_id', 'year_of_capacity_data',
       'generation_gwh_2013', 'generation_gwh_2014', 'generation_gwh_2015',
       'generation_gwh_2016', 'generation_gwh_2017', 'generation_gwh_2018',
       'generation_gwh_2019', 'generation_data_source',
       'estimated_generation_gwh_2013', 'estimated_generation_gwh_2014',
       'estimated_generation_gwh_2015', 'estimated_generation_gwh_2016',
       'estimated_generation_gwh_2017', 'estimated_generation_note_2013',
       'estimated_generation_note_2014', 'estimated_generation_note_2015',
       'estimated_generation_note_2016', 'estimated_generation_note_2017'],
      dtype='object')

/var/folders/_w/htmynbps67qc3xshbfqnl84h0000gp/T/ipykernel_97113/751800399.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df_gp = pd.read_csv("global_power_plant_database.csv")

In [7]:
df_1 = pd.read_csv("worldbank.csv")

df_1 = df_1.dropna(axis='columns', how='all')

print(df_1.head())

print("Column names:\n", df_1.columns)

  Country Name Country Code  \
0  Afghanistan          AFG
1  Afghanistan          AFG
2  Afghanistan          AFG
3  Afghanistan          AFG
4  Afghanistan          AFG

                                         Series Name              Series Code  \
0  Carbon dioxide (CO2) emissions from Building (...  EN.GHG.CO2.BU.MT.CE.AR5
1                              Coal rents (% of GDP)        NY.GDP.COAL.RT.ZS
2      Adjusted savings: energy depletion (% of GNI)        NY.ADJ.DNGY.GN.ZS
3   Adjusted savings: energy depletion (current US$)           NY.ADJ.DNGY.CD
4  Alternative and nuclear energy (% of total ene...        EG.USE.COMM.CL.ZS

  1960 [YR1960] 1961 [YR1961] 1962 [YR1962] 1963 [YR1963] 1964 [YR1964]  \
0            ..            ..            ..            ..            ..
1            ..            ..            ..            ..            ..
2            ..            ..            ..            ..            ..
3            ..            ..            ..            ..            ..
4            ..            ..            ..            ..            ..

  1965 [YR1965]  ...       2014 [YR2014]       2015 [YR2015]  \
0            ..  ...              0.5972              0.9033
1            ..  ...    0.22737000694477   0.163204860716174
2            ..  ...  0.0966641446262806  0.0559867833285066
3            ..  ...    19862746.2035553    11297542.3977155
4            ..  ...                  ..                  ..

        2016 [YR2016]      2017 [YR2017]      2018 [YR2018]  \
0              0.7121             0.6048             0.6925
1   0.249916790607737   0.40234480168601  0.541363923742697
2  0.0763640841889861  0.121057624440334  0.163438299892063
3    13897596.0742528   23176502.8071736   30416288.2185315
4                  ..                 ..                 ..

       2019 [YR2019]        2020 [YR2020]       2021 [YR2021] 2022 [YR2022]  \
0             0.5679               0.5674              0.5918        0.6013
1  0.334119584032567  0.00700147458719358  0.0193977562950517            ..
2  0.100777601807337  0.00571019277688492  0.0182028796567567            ..
3   19354353.5082382     1161018.32966959    2714217.43346233            ..
4                 ..                   ..                  ..            ..

  2023 [YR2023]
0            ..
1            ..
2            ..
3            ..
4            ..

[5 rows x 68 columns]
Column names:
 Index(['Country Name', 'Country Code', 'Series Name', 'Series Code',
       '1960 [YR1960]', '1961 [YR1961]', '1962 [YR1962]', '1963 [YR1963]',
       '1964 [YR1964]', '1965 [YR1965]', '1966 [YR1966]', '1967 [YR1967]',
       '1968 [YR1968]', '1969 [YR1969]', '1970 [YR1970]', '1971 [YR1971]',
       '1972 [YR1972]', '1973 [YR1973]', '1974 [YR1974]', '1975 [YR1975]',
       '1976 [YR1976]', '1977 [YR1977]', '1978 [YR1978]', '1979 [YR1979]',
       '1980 [YR1980]', '1981 [YR1981]', '1982 [YR1982]', '1983 [YR1983]',
       '1984 [YR1984]', '1985 [YR1985]', '1986 [YR1986]', '1987 [YR1987]',
       '1988 [YR1988]', '1989 [YR1989]', '1990 [YR1990]', '1991 [YR1991]',
       '1992 [YR1992]', '1993 [YR1993]', '1994 [YR1994]', '1995 [YR1995]',
       '1996 [YR1996]', '1997 [YR1997]', '1998 [YR1998]', '1999 [YR1999]',
       '2000 [YR2000]', '2001 [YR2001]', '2002 [YR2002]', '2003 [YR2003]',
       '2004 [YR2004]', '2005 [YR2005]', '2006 [YR2006]', '2007 [YR2007]',
       '2008 [YR2008]', '2009 [YR2009]', '2010 [YR2010]', '2011 [YR2011]',
       '2012 [YR2012]', '2013 [YR2013]', '2014 [YR2014]', '2015 [YR2015]',
       '2016 [YR2016]', '2017 [YR2017]', '2018 [YR2018]', '2019 [YR2019]',
       '2020 [YR2020]', '2021 [YR2021]', '2022 [YR2022]', '2023 [YR2023]'],
      dtype='object')

In [8]:
df_2 = pd.read_excel("World Energy Balances Highlights 2024.xlsx", 
                     sheet_name="TimeSeries_1971-2023")

df_2 = df_2.dropna(axis='columns', how='all')

print(df_2.head())

print("Column names:\n", df_2.columns)

  Source: IEA (2024). All rights reserved. (https://www.iea.org/terms)  \
0                                            Country
1                                          Australia
2                                          Australia
3                                          Australia
4                                          Australia

                 Unnamed: 1                Unnamed: 2     Unnamed: 3  \
0                   Product                      Flow      NoCountry
1  Coal, peat and oil shale           Production (PJ)  01. Australia
2  Coal, peat and oil shale              Imports (PJ)  01. Australia
3  Coal, peat and oil shale              Exports (PJ)  01. Australia
4  Coal, peat and oil shale  Total energy supply (PJ)  01. Australia

                     Unnamed: 4                    Unnamed: 5   Unnamed: 6  \
0                     NoProduct                        NoFlow         1971
1  01. Coal, peat and oil shale           01. Production (PJ)  1368.251838
2  01. Coal, peat and oil shale              02. Imports (PJ)            0
3  01. Coal, peat and oil shale              03. Exports (PJ)  -541.424001
4  01. Coal, peat and oil shale  04. Total energy supply (PJ)    884.29747

    Unnamed: 7   Unnamed: 8   Unnamed: 9  ...  Unnamed: 49  Unnamed: 50  \
0         1972         1973         1974  ...         2014         2015
1  1648.414248  1685.223676  1640.362098  ...  11950.78794  12501.00154
2            0            0            0  ...     5.240999     6.978797
3  -614.718001  -738.939398  -745.382946  ...  -10166.8869  -10634.4478
4   923.250159    945.54188    928.32307  ...    1736.5671  1797.035545

   Unnamed: 51  Unnamed: 52  Unnamed: 53  Unnamed: 54  Unnamed: 55  \
0         2016         2017         2018         2019         2020
1  12223.55369  12256.93808   12323.3258  12596.41582  12334.88697
2     6.829994     7.783701    12.364454     17.03485      19.2703
3  -10552.5051  -10248.0298  -10333.4232  -10629.0366   -10504.852
4  1863.051458  1996.773936  1930.457749  1956.712871  1782.618877

   Unnamed: 56  Unnamed: 57       Unnamed: 58
0         2021         2022  2023 Provisional
1  11467.56954  11416.06592       10961.73829
2    12.416851      15.0273         16.560904
3 -9866.188301 -9687.771298      -9149.148195
4  1683.993595  1567.046515       1624.067792

[5 rows x 59 columns]
Column names:
 Index(['Source: IEA (2024). All rights reserved. (https://www.iea.org/terms)',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18',
       'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22',
       'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42',
       'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46',
       'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50',
       'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54',
       'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58'],
      dtype='object')